# Generated by Django 2.2.2 on 2019-06-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='incorrect_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
