# Generated by Django 2.2.2 on 2019-06-24 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190620_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='box_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='last_shown_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
