# Generated by Django 2.2.2 on 2019-06-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190624_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='correct_count',
            new_name='times_correct',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='incorrect_count',
            new_name='times_incorrect',
        ),
    ]
