# Generated by Django 2.2.2 on 2019-06-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_answerrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='times_correct',
        ),
        migrations.RemoveField(
            model_name='card',
            name='times_incorrect',
        ),
    ]
