# Generated by Django 2.2.2 on 2019-06-25 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def delete_answer_records(apps, schema_editor):
    AnswerRecord = apps.get_model('core', 'AnswerRecord')
    AnswerRecord.objects.all().delete()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20190624_1620'),
    ]

    operations = [
        migrations.RunPython(delete_answer_records, do_nothing),
        migrations.AddField(
            model_name='answerrecord',
            name='user',
            field=models.ForeignKey(default=None,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stack',
            name='owner',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
