# Generated by Django 2.2.2 on 2019-06-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190625_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='box_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_shown_at',
        ),
    ]
