# Generated by Django 2.2.2 on 2019-07-02 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20190626_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_stacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
